# Generated by Django 3.1.2 on 2020-11-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_auto_20201124_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
